type = "branch"

label = "Branch 8"

[position]
x = 500
y = 380

[[outgoing]]
target = "branch-5"
weight = 1

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

[[block]]
quantity = 1
type = "Pipe"

